import "/css/style.css";
import "bootstrap/dist/css/bootstrap.min.css";
export const metadata = {
  title: "Fate Cycles",
  description: "Generated by Next.js",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
